=== IslasGECI/testmake/schemas/protocolo-geci.json
{
  "$schema": "http://json-schema.org/schema#",
  "title": "Tabular Data Package",
  "description": "Tabular Data Package is a simple specification for data access and delivery of tabular data.",
  "type": "object",
  "required": [
    "institution",
    "name"
  ],
  "properties": {
    "comment": {
      "title": "Comment",
      "description": "Miscellaneous information about the data or methods used to produce it.",
      "type": "string"
    },
    "contributors": {
      "title": "Contributors",
      "description": "The contributors to this descriptor.",
      "type": "array"
    },
    "description": {
      "title": "Description",
      "description": "A text description. Markdown is encouraged.",
      "type": "string"
    },
    "history": {
      "title": "History",
      "description": "Provides an audit trail for modifications to the original data. Well-behaved generic netCDF filters will automatically append their name and the parameters with which they were invoked to the global history attribute of an input netCDF file. We recommend that each line begin with a timestamp indicating the date and time of day that the program was executed.",
      "type": "string"
    },
    "homepage": {
      "title": "Home Page",
      "description": "The home on the web that is related to this data package.",
      "type": "string"
    },
    "institution": {
      "title": "Institution",
      "description": "Specifies where the original data was produced.",
      "type": "string"
    },
    "name": {
      "title": "Name",
      "description": "An identifier string. Lower case characters with `.`, `_`, `-` and `/` are allowed.",
      "type": "string",
      "context": "This is ideally a url-usable and human-readable name. Name `SHOULD` be invariant, meaning it `SHOULD NOT` change when its parent descriptor is updated."
    },
    "profile": {
      "title": "Profile",
      "description": "The profile of this descriptor.",
      "type": "string"
    },
    "references": {
      "title": "References",
      "description": "Published or web-based references that describe the data or methods used to produce it.",
      "type": "string"
    },
    "sources": {
      "title": "Sources",
      "description": "The raw sources for this resource.",
      "type": "array"
    },
    "title": {
      "title": "Title",
      "description": "A global attribute that is a character array providing a succinct description of what is in the dataset.",
      "type": "string"
    },
    "titulo": {
      "title": "Título",
      "description": "Traducción al español de 'title'.",
      "type": "string"
    },
    "resources": {
      "title": "Tabular Data Resources",
      "description": "An `array` of Tabular Data Resource objects, each compliant with the [Tabular Data Resource](/tabular-data-resource/) specification.",
      "type": "array",
      "items": {
        "title": "Tabular Data Resource",
        "description": "A Tabular Data Resource.",
        "type": "object",
        "required": [
          "title",
          "titulo"
        ],
        "properties": {
          "description": {
            "title": "Description",
            "description": "A text description. Markdown is encouraged.",
            "type": "string"
          },
          "id": {
            "title": "Identification",
            "description": "Cadena afanumérica (como `name` pero sin `.`, `_`, `-` ni `/`)",
            "type": "string",
            "pattern": "^([a-z0-9])+$"
          },
          "name": {
            "title": "Name",
            "description": "An identifier string. Lower case characters with `.`, `_`, `-` and `/` are allowed.",
            "type": "string",
            "pattern": "^([-a-z0-9._/])+$",
            "context": "This is ideally a url-usable and human-readable name. Name `SHOULD` be invariant, meaning it `SHOULD NOT` change when its parent descriptor is updated."
          },
          "path": {
            "title": "Path",
            "description": "A reference to the data for this resource, as either a path as a string, or an array of paths as strings. of valid URIs."
          },
          "data": {
            "title": "Data",
            "description": "Inline data for this resource."
          },
          "profile": {
            "title": "Profile",
            "description": "The profile of this descriptor.",
            "type": "string"
          },
          "source": {
            "title": "Source",
            "description": "The method of production of the original data. If it was model-generated, source should name the model and its version, as specifically as could be useful. If it is observational, source should characterize it (e.g., 'surface observation' or 'radiosonde').",
            "type": "string"
          },
          "title": {
            "title": "Title",
            "description": "A succinct description of what is in the dataset.",
            "type": "string"
          },
          "titulo": {
            "title": "Título",
            "description": "Traducción al español de `title`",
            "type": "string"
          },
          "schema": {
            "title": "Table Schema",
            "description": "A Table Schema for this resource, compliant with the [Table Schema](/tableschema/) specification.",
            "type": "object",
            "properties": {
              "fields": {
                "description": "An `array` of Table Schema Field objects.",
                "type": "array",
                "items": {
                  "title": "Table Schema Field",
                  "type": "object",
                  "required": [
                    "long_name",
                    "nombre_largo"
                  ],
                  "properties": {
                    "axis": {
                      "title": "Axis",
                      "description": "The attribute axis may be attached to a coordinate variable and given one of the values X, Y, Z or T which stand for a longitude, latitude, vertical, or time axis respectively.",
                      "type": "string"
                    },
                    "description": {
                      "title": "Description",
                      "description": "A text description. Markdown is encouraged.",
                      "type": "string"
                    },
                    "long_name": {
                      "title": "Long Name",
                      "description": "A descriptive name that indicates a variable’s content (written in English). This name is not standardized. The long_name attribute is defined by the NUG to contain a long descriptive name which may, for example, be used for labeling plots.",
                      "type": "string"
                    },
                    "name": {
                      "title": "Name",
                      "description": "This property SHOULD correspond to the name of field/column in the data file (if it has a name). As such it SHOULD be unique. Name SHOULD NOT be considered case sensitive in determining uniqueness. However, since it should correspond to the name of the field in the data file it may be important to preserve case.",
                      "type": "string"
                    },
                    "nombre_largo": {
                      "title": "Nombre Largo",
                      "description": "Traducción al espanol de long_name",
                      "type": "string"
                    },
                    "standard_name": {
                      "title": "Standard Name",
                      "description": "The name used to identify the physical quantity. A standard name contains no whitespace and is case sensitive.",
                      "type": "string"
                    },
                    "units": {
                      "title": "Units",
                      "description": "Representative units of the physical quantity. Unless it is dimensionless, a variable with a standard_name attribute must have units which are physically equivalent to the canonical units, possibly modified by an operation specified by the standard name modifier or by the cell_methods attribute or both.",
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== IslasGECI/testmake/tests/datapackage.json
{ "name": "morfometria-albatros-laysan-guadalupe",
  "homepage": "https://bitbucket.org/IslasGECI/datos-texto/src/default/datapackage/morfometria-albatros-laysan-guadalupe/",
  "profile": "tabular-data-package",
  "contributors": [
    { "title": "Mariana Salinas",
      "email": "mariana.salinas@islas.org.mx",
      "organization": "GECI",
      "role": "author"
    },
    { "title": "Yutzil Lora",
      "email": "yutzil.lora@islas.org.mx",
      "organization": "GECI",
      "role": "contributor"
    },
    { "title": "David Martínez",
      "email": "david.martinez@islas.org.mx",
      "organization": "GECI",
      "role": "contributor"
    },
    { "title": "Efren Cabrera",
      "email": "efren.cabrera@islas.org.mx",
      "organization": "GECI",
      "role": "contributor"
    },
    { "title": "Braulio Rojas",
      "email": "braulio.rojas@islas.org.mx",
      "organization": "GECI",
      "role": "contributor"
    },
    { "title": "Haran Peiro-Nuño",
      "email": "hpeiro@uabc.edu.mx",
      "organization": "GECI",
      "role": "maintainer"
    }
  ],
  "description": "Morfometría de albatros de Laysan en Isla Guadalupe (2015-2018) para determinar el dimorfismo sexual de esta especie mediante regresión logística.",
  "institution": "Grupo de Ecología y Conservación de Islas",
  "sources": [
    { "title": "Julio Hernández Montoya",
      "email": "julio.montoya@islas.org.mx"
    }
  ],
  "resources": [
    { "name": "morfometria_albatros-laysan_guadalupe",
      "path": "morfometria_albatros-laysan_guadalupe.csv",
      "profile": "tabular-data-resource",
      "description": "Morfometría de albatros de Laysan en Isla Guadalupe (2015-2018)",
      "source": "Medidas in situ",
      "title": "Laysan Albatross morphometry from Guadalupe Island",
      "titulo": "Morfometría de Albatros de Laysan en Isla Guadalupe",
      "schema": {
        "fields": [
          { "name": "fecha",
            "description": "año en que se realizó el muestreo",
            "long_name": "Year",
            "nombre_largo": "Año",
            "axis": "T",
            "standard_name": "date",
            "type": "integer",
            "constraints": {"minumum": 2015}
          },
          { "name": "subcolonia",
            "description": "Subcolonia en que se realizó en monitoreo",
            "long_name": "Subcolony",
            "nombre_largo": "Subcolonia",
            "axis": "",
            "standard_name": "",
            "type": "string",
            "constraints": {"enum": ["Punta Sur", "Zapato", "Morro Prieto"]}
          },
          { "name": "nidoPS",
            "description": "Número del nido",
            "long_name": "Nest",
            "nombre_largo": "Nido",
            "axis": "",
            "standard_name": "",
            "type": "integer",
            "constraints": {"minumum": 1}
          },
          { "name": "darvic",
            "description": "Clave de indentificación del anillo de Darvic",
            "long_name": "Darvic",
            "nombre_largo": "Darvic",
            "axis": "",
            "standard_name": "",
            "type": "string"
          },
          { "name": "sexo",
            "description": "Sexo del individuo",
            "long_name": "Sex",
            "nombre_largo": "Sexo",
            "axis": "",
            "standard_name": "",
            "type": "string",
            "constraints": {"enum": ["H", "M"]}
          },
          { "name": "longitudCraneo",
            "description": "De la parte trasera del craneo (occipital) a la punta del pico",
            "long_name": "Cranial length",
            "nombre_largo": "Longitud del cráneo",
            "axis": "",
            "standard_name": "",
            "type": "number",
            "units": "mm",
            "constraints": {"minimum": 0.01}
          },
          { "name": "longitudPico",
            "description": "Por la parte frontal del pico, justo desde la linea donde se separan pico y plumas a la punta del pico",
            "long_name": "Beak length",
            "nombre_largo": "Longitud del pico",
            "axis": "",
            "standard_name": "",
            "type": "number",
            "units": "mm",
            "constraints": {"minimum": 0.01}
          },
          { "name": "longitudNarina",
            "description": "De la mitad del orificio de la narina hasta la punta del pico",
            "long_name": "Nare length",
            "nombre_largo": "Longitud de la narina",
            "axis": "",
            "standard_name": "",
            "type": "number",
            "units": "mm",
            "constraints": {"minimum": 0.01}
          },
          { "name": "anchoCraneo",
            "description": "De lado a lado por la parte trasera de los ojos",
            "long_name": "Cranial width",
            "nombre_largo": "Ancho del cráneo",
            "axis": "",
            "standard_name": "",
            "type": "number",
            "units": "mm",
            "constraints": {"minimum": 0.01}
          },
          { "name": "altoPico",
            "description": "De la parte inferior del pico (dentario) a la altura de la narina",
            "long_name": "Beak height",
            "nombre_largo": "Alto del pico",
            "axis": "",
            "standard_name": "",
            "type": "number",
            "units": "mm",
            "constraints": {"minimum": 0.01}
          },
          { "name": "anchoPico",
            "description": "El ancho del pico justo a la altura de la narina",
            "long_name": "Beak width",
            "nombre_largo": "Ancho del pico",
            "axis": "",
            "standard_name": "",
            "type": "number",
            "units": "mm",
            "constraints": {"minimum": 0.01}
          },
          { "name": "tarso",
            "description": "Desde la coyuntura donde se une el metatarso con el peroné a la unión de las falanges con el metatarso",
            "long_name": "Tarsus length",
            "nombre_largo": "Longitud del tarso",
            "axis": "",
            "standard_name": "",
            "type": "number",
            "units": "mm",
            "constraints": {"minimum": 0.01}
          },
          { "name": "longAlaCerrada",
            "description": "Colocando el individuo en posición natural (de descanso). De el radial a la última punta de la pluma de las primarias (P9)",
            "long_name": "Closed wing length",
            "nombre_largo": "Longitud del ala cerrada",
            "axis": "",
            "standard_name": "",
            "type": "number",
            "units": "cm",
            "constraints": {"minimum": 0.01}
          },
          { "name": "longAlaAbierta",
            "description": "De la cabeza del húmero por la parte interna, a la última punta de la pluma de las primarias (P9)",
            "long_name": "Opened wing length",
            "nombre_largo": "Longitud del ala abierta",
            "axis": "",
            "standard_name": "",
            "type": "number",
            "units": "cm",
            "constraints": {"minimum": 0.01}
          },
          { "name": "mediaEnvergadura",
            "description": "Con el ala abierta. De la columna vertebral a la última punta de la pluma de las primarias (P9)",
            "long_name": "Half wingspan length",
            "nombre_largo": "Longitud de la media envergadura",
            "axis": "",
            "standard_name": "",
            "type": "number",
            "units": "cm",
            "constraints": {"minimum": 0.01}
          },
          { "name": "envergadura",
            "description": "Se obtiene a partir de la media envergadura, siendo el doble de esta",
            "long_name": "Wingspan length",
            "nombre_largo": "Longitud de la envergadura",
            "axis": "",
            "standard_name": "",
            "type": "number",
            "units": "cm",
            "constraints": {"minimum": 0.01}
          },
          { "name": "peso",
            "description": "Medida de la masa del individuo",
            "long_name": "Weight",
            "nombre_largo": "Peso",
            "axis": "",
            "standard_name": "",
            "type": "number",
            "units": "kg",
            "constraints": {"minimum": 0.01}
          }
        ],
        "missingValues": [
            "NA"
      
        ]
      }
    }
  ]
}
